#!/bin/bash

# Import the colors.
. "${HOME}/.cache/wal/colors.sh"

# Create the alias.
alias dmen='dmenu_run -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"'

tree -f -i mnt/Files/Music | dmenu -b -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -l 30 | sed -e 's/ /_/g' | xargs -r mpv 

